### ISSUE TITLE
greasemonkey may stop working after @rmottola updates

### ISSUE THREAD

**Issue by roytam1** [wicknix/Arctic-Fox#19] opened 2019-02-03 08:33 UTC
I just found that greasemonkey may stop working after long run (showing errors in javascript console, greasemonkey menu shows no active script)

some looks like unrelated errors like:

````
16:21:11.718 SyntaxError: expected expression, got '<' 1 https://www.pixiv.net/member_illust.php?mode=medium&illust_id=72417616 :1:0
````

and maybe javascript-memory related?

P.S.: the whole procedure to reproduce the issue may require opening and closing hundreds of images/html5 tabs, which makes it hard to reproduce.

possible commit range: https://github.com/wicknix/Arctic-Fox/compare/c419cb895...6b432f2

**Comment by wicknix** [comment] 2019-03-20 01:03
So far i haven't had issues with grease monkey. I use it with viewtube script on a regular basis without issue on mac osx and powerpc linux.

**Comment by rmottola** [comment] 2019-05-04 19:36
Is this still current?

**Comment by wicknix** [comment] 2019-05-04 21:33
No issue on my end yet. I only left it open in case something down the road might break it. However, since I can't reproduce this we could close it. Your thoughts?

**Closed** 2019-12-10 07:49 UTC
